name: flutter_riverpod_starter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
repository: https://github.com/mosamuhana/flutter_riverpod_starter

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  path_provider: ^2.0.11
  flutter_displaymode: ^0.5.0
  easy_localization: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.7
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
